server:
  port: 8080

static_resources_path: ../payments-app-frontend/dist/spa

corda:
  rpc:
    client:
      connection:
        host: localhost
        port: 10012
        user: user1
        password: test

participants:
  creditors:
    - bic: HSBCHKHH
      country: HK
      currency: USD
      account: 004531117838
      accountName: 'XXXX XXXX XXXX XXXX'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HSBCSGSG
      country: SG
      currency: USD
      account: 260028006178
      accountName: 'DFACSNSG ACU 260-028006-178'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HSBCLULL
      country: LU
      currency: USD
      account: LU963740101013787130
      accountName: 'LU HBEU 101-13787-130'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: MIDLGB22
      country: GB
      currency: GBP
      account: 40025050951366
      accountName: 'ALIPAY GLOBA*BCB'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: MIDLGB22
      country: GB
      currency: GBP
      account: GB77MIDL40025050951366
      accountName: 'ALIPAY GLOBA BCB'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HASEHKHH
      country: HK
      currency: USD
      account: 90000000000002
      accountName: 'TEST HK HASE'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: DBSSSGSG
      country: SG
      currency: USD
      account: 90000000000003
      accountName: 'TEST SG DBS'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HSBCSGSG
      country: SG
      currency: USD
      account: 260183041178
      accountName: 'DFACSNSG ACU 260-183041-178'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: BKCHCNBJ
      country: CN
      currency: USD
      account: 90000000000005
      accountName: 'TEST CN BOC'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
  debtors:
    - bic: HSBCHKHH
      country: HK
      currency: USD
      account: 741071328201
      accountName: 'ASCENT WAYXXXXXXXXXX'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HSBCSGSG
      country: SG
      currency: USD
      account: 260183041178
      accountName: 'DFACSNSG ACU 260-183041-178'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HSBCLULL
      country: LU
      currency: USD
      account: LU953740101006823130
      accountName: 'DFACSNGB MDBK 634-532865-130'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: MIDLGB22
      country: GB
      currency: GBP
      account: 40032862001802
      accountName: 'Alipay SINGAPORE E-COMMERCE PTE LTD'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HSBCSGSG
      country: SG
      currency: GBP
      account: 260476940193
      accountName: 'DFACSNSG ACU 260-476940-193'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: CITIHKHX
      country: HK
      currency: USD
      account: 90000000000001
      accountName: 'TEST HK CITI'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: DBSSSGSG
      country: SG
      currency: USD
      account: 90000000000003
      accountName: 'TEST SG DBS'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HASEHKHH
      country: HK
      currency: USD
      account: 90000000000002
      accountName: 'TEST HK HASE'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: CITIUS33
      country: US
      currency: USD
      account: 90000000000004
      accountName: 'TEST US CITI'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HSBCHKHH
      country: HK
      currency: USD
      account: 500295639201
      accountName: 'XXXXXXXXX XXXXXXXXX'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HSBCHKHH
      country: HK
      currency: USD
      account: 001000389201
      accountName: 'XXXX XXXX XXXX XXXX'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
    - bic: HSBCLULL
      country: LU
      currency: USD
      account: LU851670001001775145
      accountName: 'S-1-1775'
      effectiveDate: 2022-10-01
      expiryDate: 2023-10-01
      paymentLimit: 1000000
