name: GitHub Actions - Tagged release
on:
  # On tag push, build and publish new release
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'
      - name: 'Build'
        run: ./gradlew build --no-daemon

      - name: 'Create checksum'
        run: |
          cd contracts/build/libs/
          ls | xargs -I {} sh -c 'sha256sum "{}" > {}.sha256'
          cd ../../../
          cd workflows/build/libs/
          ls | xargs -I {} sh -c 'sha256sum "{}" > {}.sha256'

      - name: 'Release'
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            contracts/build/libs/*
            workflows/build/libs/*
