# On tag push, build and publish new release

name: GitHub Actions - Tagged release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-publish-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'
      - name: 'Build'
        run: ./gradlew :payments-contracts:build :payments-workflows:build -Pversion=${GITHUB_REF_NAME:1} --no-daemon

      - name: 'Create checksum'
        run: |
          cd contracts/build/libs/
          ls | xargs -I {} sh -c 'sha256sum "{}" > {}.sha256'
          cd ../../../
          cd workflows/build/libs/
          ls | xargs -I {} sh -c 'sha256sum "{}" > {}.sha256'

      - name: 'Build Dokka API reference'
        run: ./gradlew dokkaHtmlMultiModule

      # Push HTML files to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/htmlMultiModule

      - name: 'Release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            contracts/build/libs/*
            workflows/build/libs/*
