name: GitHub Actions - Build
on:
  # On pull request, call build to check if pull request can be accepted
  pull_request:
  # Build master all the time it is being pushed or merged into
  push:
    branches:
      master

jobs:
  build-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'
      - name: 'Build'
        run: ./gradlew build --no-daemon
